name: Coremark benchmarking of hosted runner
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run coremark
      run: make XCFLAGS="-DMULTITHREAD=4   -DUSE_FORK"
    - name: Show results
      run: cat ./run1.log
